####################################
### -- HeavySpleef  -  Config -- ###
### Developed by matzefratze123  ###
####################################
#
# This is the main configuration file of HeavySpleef.
# Use /spleef save to save games instantly

# Should the plugin be able to download a new version of
# HeavySpleef if there is an update avaible? (/spleef update)
# You'll find updates in the folder /plugins/update
# The plugin will be auto installed by bukkit at the next
# server reload / restart...
auto-update: true

general:
  
  # How far away should spleefmessages be broadcasted for players?
  # This works if the message announce is set to radius.
  broadcast-radius: 40
  
  # Which spleef prefix should we use?
  spleef-prefix: '&8[&6&lSpleef&8]'
  
  # Should arenas be protected?
  protectArena: true
  
  # Should the built-in HeavySpleef selection system be used
  # or the WorldEdit wand selection? (allowed values: WorldEdit, HeavySpleef)
  wandType: 'HeavySpleef'
  
  # Which wand tool should be used?
  # (Default: 280 = Stick)
  # Only works if wandType is set to 'HeavySpleef'
  wandItem: 280
  
  # Command Whitelist
  # A list of commands that users can use while spleefing...
  commandWhitelist:
  - /spleef
  - /money
  - /msg
  - /message
  - /m
  - /tell
  - /t
  - /r
  - /reply
  - /mail
  - /ban
  - /kick
  - /pardon
  - /unban
  
  # How long should the countdown between a round be?
  countdownBetweenRound: 5
  
  # Should the autostart-vote feature be enabled?
  autostart-vote-enabled: true
  
  # Set how many procent of votes must be received
  # to start the game. This means that x percent of
  # players need to do /spleef vote or /spleef ready
  # to autostart the game (Only if you don't want to
  # use /spleef start)
  autostart-vote: 70
  
  # A list of vips on your server
  # Vip's will have a dark red name
  # in spleef broadcasts
  vip:
  - someone
  - anotherone
  
  # PVP Timer:
  # Some servers don't want that players can instantly
  # teleport to a spleef game to escape from a battle.
  # Here you can configure an amount of x seconds they have
  # to wait until they can join a spleef game. 
  # Set this to 0 to disable this function
  pvptimer: 0
  
  # This is the ready block for players who don't want to use
  # /spleef ready or /spleef vote
  # (Hit the block)
  ready-block: IRON_BLOCK
  
leaderboard:
  # Points for Spleef Games
  win: 30
  lose: -4
  knockout: 3
  gamePlayed: 3

messages:
  # Decide wether the following messages should be broadcasted
  # around the game (radius), global (global) or only for ingame players (ingame)
  
  game-disable: radius
  game-enable: radius
  game-start-info: radius
  game-countdown: ingame
  game-stop: radius
  player-join: radius
  player-lose: radius
  knockouts: radius
  win: radius
  timeout: radius
  floor-regeneration: radius

flag-defaults:
  # A list of all default values for flags...
  # Please note that these values are the DEFAULT
  # values. This means that this values will only be 
  # used if there is no specified game flag!
  # Set specified game flags with /spleef flag <arena> <flag> <value>
  
  minplayers: 2
  maxplayers: 0
  autostart: 0
  countdown: 10
  jackpotamount: 0
  reward: 0
  chances: 0
  timeout: 0
  rounds: 3
  
  1vs1: false
  shovels: false
  shears: false
  team: false
  splegg: false
  boxes: true
  blockbreakeffect: false
  
  # Syntax of an array itemreward flag: 'ID AMOUNT ID2 AMOUNT2 ID3 AMOUNT3 etc.'
  # Example: '264 5 388 3'. This would give 5 Diamonds and 3 Emeralds
  itemreward: ''
  losereward: ''
  
  # Syntax of an single itemstack flag: '<id:data> [amount]'
  icon: '277 1'
  
  difficulty: MEDIUM

queues:
  
  # Should queues be enabled?
  useQueues: true
  
  # Should users be allowed to use commands while in queue?
  # If you don't want that players join a spleef queue and
  # another minigame queue set this to false (You can set
  # a queues lobby with /spleef setqueuelobby <name>)
  commandsInQueue: false

scoreboards:
  # Which id should numbers of scoreboards have?
  # Please use ''
  fontID: '35:14' # Red wool
  
  # Which id should the other blocks of the scoreboard have?
  # Please use ''
  baseID: '35:15' # Black wool

language:

  # Language that should be used
  # Preinstalled languages: en, de, ru
  # Feel free to translate an own language file
  # and contact me via a PM on dev.bukkit.org to add it
  # if you want to :)
  language: en
  
  # Should messages be editable?
  # If you set this to true, you
  # find language files in the folder
  # /plugins/HeavySpleef/language
  editable: false 

anticamping:

  # Should the anti-camping feature be enabled?
  # If true, players can't camp in corners to win
  # the game! They will be teleported a floor down if they camp...
  enabled: true

  # Should a player be warned of camping?
  campWarn: true

  # At how many seconds of camping should a warning be send to the player?
  # (Only works if campWarn is set to true)
  warnAt: 3
  
  # At how many seconds of camping should a player teleported one floor down?
  teleportAt: 6
  
sounds:

  # Should a pling sound be played if a player joins a game? This sound
  # will be only heared by players that joined the game...
  plingSound: true
  
  # Should a levelup sound be played to the player that wins the game?
  levelUp: true
  
statistic:

  # Which database type should be used for statistic database storing?
  # Allowed types: 'yaml', 'mysql'
  dbType: yaml
  
  # If you use mysql you have to fill the following things:
  
  host: 'localhost'
  port: '3306'
  databaseName: ''
  user: 'root'
  password: ''
  
# How much... No, you've finished the configuration ;)
