name: HeavySpleef
description: Easy to use spleef plugin for bukkit

version: Dev 1.4.2
author: matzefratze123

# Load WorldManagement Plugins before HeavySpleef
softdepend: [Vault, WorldEdit, TagAPI, Multiverse-Core, MultiWorld]
website: http://dev.bukkit.org/server-mods/heavyspleef/

main: de.matzefratze123.heavyspleef.HeavySpleef

commands:
  spleef:
    aliases: [hs, hspleef, spl, splegg]
    description: General Spleef command for HeavySpleef
